import { useEffect, useState } from 'react'
import Head from 'next/head'
import Message from '../components/Message'
import { db } from '../utils/firebase'
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import Link from 'next/link';


export default function Home() {
  const [allPost, setAllPost] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, 'posts');
    const q = query(collectionRef, orderBy('timestamp', 'desc'));
    const onsubscribe = onSnapshot(q, (snapshop) => {
      setAllPost(snapshop.docs.map((doc) => ({...doc.data(), id: doc.id})));
    });
    return onsubscribe;
  }

  useEffect(() => {
    getPosts();
  }, [])
  
  return (
    <div>
      <Head>
        <title>Creative - Writes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='my-12 text-lg font-medium'>
        <h2 className='text-md text-gray-400 font-black'>Mira lo que otra gente cuenta...</h2>
        {allPost.map(post => (
          <Message {...post} key={post.id}>
            <Link href={{ pathname: `/${post.id}`, query: {...post} }}>
              <button className='text-xs text-gray-600 font-black'>{post.comments?.length >0 ? post.comments?.length : '0' } comentarios</button>
            </Link>
          </Message>
        ))}
      </div>
    </div>
  )
}
